---
- name: Webhook demo prints all incoming events
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ port | default(5556) }}"
        host: 0.0.0.0
        hmac_secret: "secret"
        hmac_algo: "sha256"
        hmac_header: "x-hub-signature-256"
        hmac_format: "base64"
  rules:
    - name: Webhook rule
      condition: true
      action:
        print_event:
          pretty: true
...
