---
- name: Listen for events on a webhook
  hosts: 10.46.29.185
  ## Define our source for events
  sources:
    - ansible.eda.url_check:
        urls:
          - http://10.46.29.185:8098
        delay: 10

  rules:
    ## Define the conditions we are looking for
    - name: Web site is up
      condition: event.url_check.status == "up"
    ## Define the action we should take should the condition be met
      action:
        run_job_template:
          organization: Default
          name: wowza

    - name: Web site is down
      condition: event.url_check.status == "down"
    ## Define the action we should take should the condition be met
      action:
        run_job_template:
          organization: Default
          name: fix_web
