---
- name: Listen for Splunk webhook events
  hosts: localhost
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 9998
  ## Define the conditions we are looking for
  rules:
    - name: Process Splunk webhook payload
      condition:
        all:
         - event.payload.sid is defined
      ## Define the action we should take when the condition is met
      action:
        run_job_template:
          name: splunk_eda_ta
          organization: Default
          ## To pass job args to AAP EDA, check "Prompt on launch" checkbox in "Extra variables" line on the job template 
          job_args:
            extra_vars:
              rulebook_action_var: "Use this to pass vars from rulebook to playbook"
